# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I2DgrTfkRPWl9OYtTsrt3dy2DhE1CUM6
"""


# =========================
# IMPORTS

# =========================
import cv2
import torch
import numpy as np
from ultralytics import YOLO
import torchvision.models as models
import torch
# =========================
# PATHS ()
# =========================
video_path = "inputvideo.mp4"
output_video_path = "output_fighting_detection.mp4"

# ✅ USE YOUR best.pt HERE
yolo_model_path = "best.pt"

# ✅ Your classifier weights
classifier_model_path ="classification_model.pt"

# =========================
# LOAD MODELS
# =========================

# YOLO model (FIXED)
yolo_model = YOLO(yolo_model_path, task='detect')

# Classifier model (FIXED)
classifier = models.resnet18(weights=None)
classifier.fc = nn.Linear(classifier.fc.in_features, 2)

classifier.load_state_dict(torch.load(classifier_model_path, map_location="cpu"))
classifier.eval()

# Labels
class_names = ["Normal", "Fighting"]

# =========================
# PREPROCESS FUNCTION
# =========================
def preprocess(image):
    img = cv2.resize(image, (224, 224))
    img = img / 255.0
    img = np.transpose(img, (2, 0, 1))  # HWC → CHW
    img = np.expand_dims(img, axis=0)
    img = torch.tensor(img, dtype=torch.float32)
    return img

# =========================
# VIDEO SETUP
# =========================
cap = cv2.VideoCapture(video_path)

if not cap.isOpened():
    raise ValueError("❌ Error opening video file")

width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = cap.get(cv2.CAP_PROP_FPS)

fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter(output_video_path, fourcc, fps, (width, height))

# =========================
# PROCESS VIDEO
# =========================
while True:
    ret, frame = cap.read()
    if not ret:
        break

    # YOLO detection
    results = yolo_model(frame)

    for box in results[0].boxes:
        cls_id = int(box.cls[0])

        # Detect PERSON only (COCO class 0)
        if cls_id != 0:
            continue

        x1, y1, x2, y2 = map(int, box.xyxy[0])

        # Safety clamp (avoid crop errors)
        x1, y1 = max(0, x1), max(0, y1)
        x2, y2 = min(frame.shape[1], x2), min(frame.shape[0], y2)

        person_crop = frame[y1:y2, x1:x2]

        if person_crop.size == 0:
            continue

        # =========================
        # CLASSIFICATION
        # =========================
        input_tensor = preprocess(person_crop)

        with torch.no_grad():
            outputs = classifier(input_tensor)
            pred = torch.argmax(outputs, dim=1).item()

        label = class_names[pred]

        # =========================
        # DRAW RESULTS
        # =========================
        color = (0, 0, 255) if label == "Fighting" else (0, 255, 0)

        cv2.rectangle(frame, (x1, y1), (x2, y2), color, 2)
        cv2.putText(frame, label, (x1, y1 - 10),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.8, color, 2)

    # Write frame
    out.write(frame)

# =========================
# CLEANUP
# =========================
cap.release()
out.release()

print("✅ Done! Video saved as:", output_video_path)